### ISSUE TITLE
Results are too big to render in a browser

### ISSUE THREAD

**Issue by boryashkin** [pinba-server/pinba-server#1]
We just set everything up as per the instruction, but in result we got huge chunks of data returned by several queries into our browsers

![image](https://user-images.githubusercontent.com/5726656/57693663-33898080-7663-11e9-8b62-41a1fb5846bf.png)

For example this one returns 16.6MB of data and it takes 2 minutes to just execute:
```sql
WITH (CASE          WHEN (6000 % 60) = 0 THEN 6000     ELSE 60 END ) AS scale 
SELECT     intDiv(toUInt32(timestamp), scale) * scale * 1000 AS t,     SUM(req_count) * 60 / scale as req_count,     script_name || ':' || toString(status) as script_name 
FROM pinba.report_by_all WHERE     timestamp >= toDateTime(1557658981)     AND CASE 
WHEN 'all' <> 'all' THEN schema = 'all' ELSE 1 END     AND CASE WHEN 'all' <> 'all' THEN hostname = 'all' ELSE 1 END     AND CASE WHEN 'all' <> 'all' THEN server_name = 'all' ELSE 1 END
GROUP BY script_name, t 
ORDER BY t, req_count desc FORMAT JSON
```
We have 2M rows of data in our DB (that's not so much, i think), but it already **doesn't work**, browser's tab just freeezes.

Has anyone run into the same problem?

**Comment by morozovsk** [comment]
Я сталкивался с подобной проблемой. Скорее всего у вас большое количество уникальных страниц сайта. Т.е. проблема даже не в 16 мб - это не много. Проблема в том, что графана пытается построить очень много линий на графике.
Две недели назад я добавил [хак](https://github.com/pinba-server/pinba-server/blob/master/clickhouse/pinba.report_by_all.sql#L90), который "схлопывает" такие адреса страниц:

`/*/*.*`

например:

```
/css/main.css -> /css/*
/css/layout.css -> /css/*
```

Этот хак помогает пожалуй только для тех случаев, когда вы отправляете в пинбу данные из nginx (установили модуль для nginx).
Если у вас метрики идут только с php, тогда он не поможет.
Но ваша проблема решается похожим способом, даже пара:
1) нужно схлопывать урл, например,

```
/qwe/qwe/qwe -> /qwe/*
/qwe/qwe/qwe -> /qwe/*
/asd/asd/asd -> /asd/*
```

Это можно сделать с помощью sql запроса, Я могу написать конкретный запрос для измеения materialized view
2) нужно отбрасывать "мусорные" урл - единичные урл, которые ни на что особо не влияют, но сильно засоряют дашборд, например изменив запрос в графане, добавив:
`HAVING req_count > 1`

Для дальнейшей вам помощи мне нужно больше информации.
1) 2 миллиона записей у вас в requests или report_by_all? У меня в report_by_all 3 миллиона
`SELECT COUNT(*) FROM report_by_all`
2) сколько у вас уникальных script_name? У меня меньше 200.
`SELECT COUNT(DISTINCT script_name) FROM report_by_all`

**Comment by boryashkin** [comment]
Действительно, дело в этом
```sql
SELECT COUNT(DISTINCT script_name) FROM report_by_all /* = ~200K */

SELECT COUNT(*) FROM report_by_all /* = 900K */

SELECT count(DISTINCT script_name) FROM report_by_all WHERE req_count > 1 /* а так уже  11.5K */
```
Спасибо, направление теперь понятно, будем оптимизировать

**Comment by morozovsk** [comment]
Также вашу проблему можно решить добавлением в графане в первый запрос строки:
`AND script_name in (SELECT script_name || ':' || toString(status) as script_name FROM report_by_all WHERE $timeFilter GROUP BY script_name ORDER BY sum(req_count) DESC LIMIT 50)`
Тогда будут отображаться только топ 50 script_name.
Подобные запросы можно написать для остальных графиков.

**Comment by petqa** [comment]
Приветствую! Проблема актуальна, добавлял данный запрос, не помогает

**Comment by morozovsk** [comment]
Нашёл более простой способ. Кликхаус уже давно подерживает в запросах конструкцию "LIMIT n BY column_name".
В данном случает в конце запроса нужно просто добавить:
` LIMIT 10 by t`
Т.о. для каждой временной отметки t будет отобрано только 10 значений. В идеале это будет 10 линий.

**Comment by petqa** [comment]
Я так понимаю графана нам по итогу должна отдать 10 строчек?
Я может что-то не так делаю, добавляю в fomattedQuery LIMIT 10 BY t, эффекта нуль. Проверяю запросы все прямиком из графаны

**Comment by morozovsk** [comment]
да

**Comment by petqa** [comment]
Оставил просто limit, добавил так же req_count > 1
Страница начала грузиться и отдавать данные, но пропали графики
В какую сторону еще можно смотреть?

**Comment by petqa** [comment]
Судя по network запросы все еще не проходят все

**Comment by petqa** [comment]
Разобрался, спасибо
Но появилась новая проблема, графики перестали работать через graph, с помощью bar gauge все корректно и через остальные так же
