### ISSUE TITLE
Does it works from php cli?

### ISSUE THREAD

**Issue by denisgolius** [pinba-server/pinba-server#2]
We have **php cli** that runs from screen in manual mode. Will it works in this situtation?

**Comment by morozovsk** [comment]
Yes
https://habr.com/ru/post/444610/
В разделе "Лайфхаки" я описал, как удобно можно разделять статистику по php-fpm и php-cli

**Comment by denisgolius** [comment]
Dockerfile is not correct

cp: cannot create regular file '/usr/lib64/nginx/modules/ngx_http_pinba_module.so': No such file or directory

Today I will send pull request to you - maybe it will be ok

**Comment by morozovsk** [comment]
Yes, [ubuntu docker file](https://github.com/pinba-server/pinba-server/blob/ad91c45165af6c706bb1b82517a24cd678d3249f/docker/ubuntu18.04/Dockerfile#L44) has problem because https://github.com/tony2001/ngx_http_pinba_module/issues/15

**Comment by morozovsk** [comment]
Sorry. tony2001/ngx_http_pinba_module#15 is already fixed.
Current problem in docker file [is also fixed](https://github.com/pinba-server/pinba-server/commit/5cfdb8d186b4b5733e20daa9f592a7ab0feedca6).
