### ISSUE TITLE
Данные не идут в ClickHouse как найти причину?

### ISSUE THREAD

**Issue by DimNS** [pinba-server/pinba-server#3]
Добрый день, воспользовались вот этой инструкцией https://habr.com/ru/post/444610/, установили protobuf.so, pinba.so для php 7.2 и в Grafana пусто.

В настройках Grafana подключение к ClickHouse настроено и тест подключения проходит успешно

Как можно проверить что данные идут в порт 30002 ?

Через консоль подключались к clickhouse-client и делали SELECT по таблицам из дампа, таблицы есть, но везде пусто

Что мы делаем не так?

CentOS Linux release 7.7.1908 (Core)

Ещё в Grafana после установки готового шаблона вылазит ошибка
![2020-02-19_12-17-14](https://user-images.githubusercontent.com/8703922/74810797-f8af2a00-5311-11ea-986f-bb792b2a9b6b.jpg)

**Comment by morozovsk** [comment]
1. Нужно убедиться, что phpinfo присутствуют модули protobuf и pinba
2. Нужно остановить pinba-server и запустить команду для поднятия простого udp-сервера
>nc -u -l 127.0.0.1 30002

если в консоли ничего не отображается, значит данные в него не идут, а это значит, что что-то в php.ini не было настроено.

3. если данные идут, то значит что pinba-server их получает, но не может записать в кликхаус.

4. если у вас не получается подключиться из графаны к кликхаусу, возможно кликхауст настроен неверно либо графана. 
нужно проверить логи графаны и кликхауса.

**Comment by DimNS** [comment]
1. Модули protobuf и pinba загружены, в phpinfo показываются
2. pinba-server остановили и запустили простой udp-сервер, данные идут, хотя бы тут всё хорошо модуль работает
3. Похоже что-то не так с ClickHouse, разбираемся

UPDATE
pinba-server успешно пишет в ClickHouse, таблицы наполняются, похоже проблема в связке Grafana и ClickHouse

**Comment by DimNS** [comment]
pinba-server успешно пишет в ClickHouse, таблицы наполняются, похоже проблема в связке Grafana и ClickHouse

**Comment by DimNS** [comment]
У нас всё получилось

вот эта команда выручает понять где затык
nc -u -l 127.0.0.1 30002

А еще попытка остановить pinba-server выявила то, что он даже не был запущен ) после запуска пошли данные в ClickHouse

Ну и в Grafana неправильно был настроен коннект к ClickHouse (выбран метод соединения: Browser вместо Server), спутал конфиг ClickHouse в котором порт значится как http, а это ведь браузер да )) А ещё Grafana при попытке коннекта не выдает ошибку, а просто пишет "Test..." и закрывает окошко, а вверху пишет "DataSource updated", а вот когда тест действительно прошел успешно вылезло внизу зеленое окошко об успешном подключении

Спасибо вам за инструмент, в принципе все легко, но вот есть разные нюансы с настройками
